spring.security.oauth2.client.registration.kakao.client-id: c3fd7ee121c229e092ecaf7a67960298
spring.security.oauth2.client.registration.kakao.client-secret: 95i43gMteAlEXkkZvjKKyADCvsNvwkd7
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: heyjigi@gmail.com
    password: zlzlemr66^^
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
