spring:
  profiles:
    active: local

---
spring:
  profiles: local

  # hikari
  datasource:
    platform: h2
    hikari:
      url: jdbc:h2:mem:testdb;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver

  # jpa
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect